export const Users = [
  {
    id: 1,
    profilePicture: "/assets/profiles/profile.jpg",
    username: "Shahmar Aliyev",
  },
  {
    id: 2,
    profilePicture: "assets/profiles/kobe.jpg",
    username: "Kobe Bryant",
  },
  {
    id: 3,
    profilePicture: "assets/profiles/curry.jpg",
    username: "Stephen Curry",
  },
  {
    id: 4,
    profilePicture: "assets/profiles/4.jpg",
    username: "Rihanna",
  },
  {
    id: 5,
    profilePicture: "assets/profiles/5.jpg",
    username: "Thomas Lewandowski",
  },
  {
    id: 6,
    profilePicture: "assets/profiles/6.jpg",
    username: "Kylian Mbappe",
  },
  {
    id: 7,
    profilePicture: "assets/profiles/7.jpg",
    username: "Dwayne Wade",
  },
  {
    id: 8,
    profilePicture: "assets/profiles/8.jpg",
    username: "Tom Hanks",
  },
  {
    id: 9,
    profilePicture: "assets/profiles/9.jpg",
    username: "J. F. Kennedy",
  },
  {
    id: 10,
    profilePicture: "assets/profiles/10.jpg",
    username: "Drake",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/posts/doco.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/posts/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/posts/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/posts/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/posts/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/posts/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/posts/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/posts/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/posts/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/posts/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
